version: '3'
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    image: test:local
    container_name: "test_app"
    hostname: test.local:127.0.0.1
    volumes:
      - /Users/alisovskiy/dev/TEST:/var/www/html
      - /Users/alisovskiy/dev/TEST/log:/var/log
#    environment:
#      DB_HOST: mysql
#      DB_DATABASE: test
#      DB_USERNAME: root
#      DB_PASSWORD: Lisman27